# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('registered_name', models.CharField(blank=True, max_length=50, verbose_name='razón social')),
                ('cif_nif', models.CharField(blank=True, max_length=10, verbose_name='cif/nif')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='dirección')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('economic_sector', models.CharField(blank=True, max_length=100, verbose_name='sector económico')),
                ('legal_form', models.CharField(blank=True, choices=[('autónomo', 'trabajador autónomo'), ('cooperativa', 'cooperativa'), ('SL', 'sociedad de responsabilidad limitada (S.L.)'), ('comunidad de bienes', 'comunidad de bienes'), ('SA', 'sociedad anónima (S.A.)'), ('SC', 'sociedad civil'), ('otro', 'otro')], max_length=100, verbose_name='forma jurídica')),
                ('legal_form_other', models.CharField(blank=True, max_length=100, verbose_name='forma jurídica (otros)')),
                ('number_of_employees', models.CharField(blank=True, choices=[('0', '0 (emprendedor-trabajador)'), ('1-3', '1-3'), ('4-10', '4-10'), ('11-25', '10-25'), ('26-50', '26-50'), ('51-100', '51-100'), ('+100', '+100')], max_length=20, verbose_name='número de empleados')),
                ('turnover', models.PositiveIntegerField(blank=True, null=True, verbose_name='facturación')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='persona de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='teléfono de contacto')),
                ('ecg_link_person', models.CharField(blank=True, max_length=100, verbose_name='contacto en la EBC')),
                ('ecg_field', models.CharField(blank=True, max_length=100, verbose_name='campo de energía')),
                ('ecg_seed', models.CharField(choices=[('-', 'simpatizante'), ('1', 'semilla 1'), ('2', 'semilla 2'), ('3', 'semilla 3')], max_length=1, verbose_name='semilla EBC')),
                ('balance_date', models.DateField(blank=True, null=True, verbose_name='fecha del balance')),
                ('balance_version', models.CharField(blank=True, choices=[('4.1', '4.1'), ('Rubi-Brilla (RB)-Zaragoza', 'Rubi-Brilla (RB)-Zaragoza'), ('Versiones anteriores', 'Versiones anteriores'), ('5.0', '5.0'), ('otra', 'otra')], max_length=20, verbose_name='versión utilizada de la matriz')),
                ('balance_version_other', models.CharField(blank=True, max_length=100, verbose_name='versión utilizada (otros)')),
                ('global_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación global')),
                ('consultant', models.CharField(blank=True, max_length=100, verbose_name='consultor')),
                ('auditor', models.CharField(blank=True, max_length=100, verbose_name='auditor')),
                ('evaluation', models.TextField(blank=True, verbose_name='valoración y buenas prácticas detectadas')),
                ('score_a1', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación A1')),
                ('score_b1', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación B1')),
                ('score_c1', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación C1')),
                ('score_c2', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación C2')),
                ('score_c3', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación C3')),
                ('score_c4', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación C4')),
                ('score_c5', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación C5')),
                ('score_d1', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación D1')),
                ('score_d2', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación D2')),
                ('score_d3', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación D3')),
                ('score_d4', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación D4')),
                ('score_d5', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación D5')),
                ('score_e1', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación E1')),
                ('score_e2', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación E2')),
                ('score_e3', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación E3')),
                ('score_e4', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación E4')),
                ('score_e5', models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación E5')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
    ]
