# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgdir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='balance_version_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='versión utilizada (otra)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('autonomo', 'trabajador autónomo'), ('cooperativa', 'cooperativa'), ('SL', 'sociedad de responsabilidad limitada (S.L.)'), ('comunidad de bienes', 'comunidad de bienes'), ('SA', 'sociedad anónima (S.A.)'), ('SC', 'sociedad civil'), ('otra', 'otra')], max_length=100, verbose_name='forma jurídica'),
        ),
    ]
