# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('ecgdir', '0003_auto_20170110_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='address_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='portal / piso / puerta'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_street_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='calle y número'),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.CITIES_CITY_MODEL, verbose_name='población'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='página web'),
        ),
        migrations.AddField(
            model_name='organization',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='balance_version',
            field=models.CharField(blank=True, choices=[('4.0', '4.0'), ('4.1', '4.1'), ('5.0', '5.0'), ('Rubi-Brilla (RB)-Zaragoza', 'Rubi-Brilla (RB)-Zaragoza'), ('Versiones anteriores', 'Versiones anteriores'), ('otra', 'otra')], max_length=20, verbose_name='versión utilizada de la matriz'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('comunidad de bienes', 'Comunidad de bienes'), ('empresario individual', 'Empresario individual'), ('sociedad anonima', 'Sociedad anónima (S.A.)'), ('sociedad civil', 'Sociedad civil'), ('cooperativa', 'Sociedad cooperativa'), ('sociedad laboral', 'Sociedad laboral'), ('sociedad limitada', 'Sociedad limitada (S.L.)'), ('otra', 'otra')], max_length=100, verbose_name='forma jurídica'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='number_of_employees',
            field=models.CharField(blank=True, choices=[('1', '1 (emprendedor-trabajador)'), ('2', '2'), ('3-5', '3-5'), ('6-10', '6-10'), ('11-20', '11-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('101-200', '101-200'), ('201-350', '201-350'), ('351-500', '351-500'), ('501-750', '501-750'), ('751-1000', '751-1000'), ('1001-1500', '1001-1500'), ('1501-2500', '1501-2500'), ('>2500', '>2500')], max_length=20, verbose_name='número de empleados'),
        ),
    ]
