# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgdir', '0004_auto_20170117_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
    ]
