# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgdir', '0005_remove_organization_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='población'),
        ),
    ]
