# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgdir', '0006_organization_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='activa'),
        ),
    ]
