# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgdir', '0008_auto_20170117_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='score_a2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación A2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_a3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación A3'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_a4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación A4'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_a5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación A5'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_b2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación B2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_b3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación B3'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_b4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación B4'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_b5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación B5'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N1'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n10',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N10'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n11',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N11'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n12',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N12'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n13',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N13'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n14',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N14'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n15',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N15'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n16',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N16'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n17',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N17'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N3'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N4'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N5'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N6'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N7'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N8'),
        ),
        migrations.AddField(
            model_name='organization',
            name='score_n9',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntuación N9'),
        ),
    ]
